services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: "postgres-tutorials"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - dbcult:/data/postgres-dbcult
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  dbcult:
    external: true