services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: "postgres-tutorials"
    container_name: cultist
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: master_password
      PGDATA: '/data/postgres-cultist'
    volumes:
      - dbcult:/data/postgres-dbcult
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  dbcult:
    external: true